WINDOW_WIDTH=400
WINDOW_HEIGHT=400
WINDOW_TITLE='Gold collector'
WINDOW_BACKGROUND_COLOR='WHITE'

PLAYER_WIDTH=40
PLAYER_HEIGHT=40
PLAYER_SPEED=4
PLAYER_TIME=3
PLAYER_COLOR='BLUE'

GOLDEN_WIDTH=25
GOLDEN_HEIGHT=25
GOLDEN_COLOR='YELLOW'

FONT_SIZE=20
FONT_COLOR='BLACK'
FONT_FAMILY_PATH='./assets/fonts/ARCADECLASSIC.TTF'

PATH_SOUND_1='./assets/sounds/sound-1.mp3'
PATH_SOUND_2='./assets/sounds/sound-2.mp3'
PATH_SOUND_3='./assets/sounds/sound-3.mp3'

PATH_ICON='./assets/images/icon.ico'

FPS = 60